# Blog settings
permalink: /blog/:title


# My variables
name: Aaron's blog 
description: I like coding
google_verification: null


# RSS 
gems:
  - jekyll-feed
  - jekyll-gist


# File management
include: [".htaccess"]
exclude: ["README.md", "LICENSE"]


# Sass
sass:
  style: :compressed
  sass_dir: _sass


# Markdown
markdown: redcarpet
redcarpet:
  extension:
    - fenced_code_blocks
highlighter: pygments
