# Blog settings
permalink: /blog/:title

# My variables
name: Aaron's blog
description: Software engineering in story form

# RSS
plugins:
  - jekyll-feed
  - jekyll-gist
  - octopress-minify-html

# File management
include: [".htaccess"]
exclude: ["README.md", "LICENSE","new_draft.sh","publish_draft.sh","run_drafts.sh", "Gemfile", "Gemfile.lock", "Dockerfile", "Jenkinsfile", "version.txt", "nginx.conf"]

# Sass
sass:
  style: :compressed
  sass_dir: _sass

# Markdown
markdown: kramdown
kramdown:
  input: GFM
