version: '1.0'
stages:
  - build
  - canary25
  - canary50
  - canary75
  - release
steps:
  clone:
    stage: build
    title: Clone
    type: git-clone
    arguments:
      repo: 'abatilo/blog'
      git: github
      revision: 'master'
  previous_version:
    stage: build
    title: Get Previous Version
    type: freestyle
    arguments:
      image: 'codefresh/kubectl:latest'
      working_directory: 'blog/'
      commands:
        - cf_export PREVIOUS_VERSION=$(kubectl --context chopper -n applications get deployment blog -o jsonpath='{.spec.template.spec.containers[0].image}' | cut -d':' -f2)
  version:
    stage: build
    title: Get Version
    type: freestyle
    arguments:
      image: 'alpine:latest'
      working_directory: 'blog/'
      commands:
        - cf_export VERSION=$(cat version.txt)
  build:
    stage: build
    title: Build
    type: build
    image_name: 'abatilo/blog'
    working_directory: 'blog'
    tag: ${{VERSION}}
  install_25:
    stage: canary25
    image: 'codefresh/cfstep-helm:2.9.1'
    title: Install
    environment:
      - CHART_REF=blog/blog
      - RELEASE_NAME=blog
      - KUBE_CONTEXT=chopper
      - NAMESPACE=applications
      - VALUESFILE_prod='blog/blog/values.yaml'
      - VALUE_image_repository='r.cfcr.io/abatilo/abatilo/blog'
      - VALUE_image_tag='${{PREVIOUS_VERSION}}'
      - VALUE_canary_enabled=true
      - VALUE_canary_percentage=25
      - VALUE_canary_tag='${{VERSION}}'
  timeout_25:
    stage: canary25
    type: pending-approval
    title: Step Title
    description: Step description
    timeout:
      duration: 0.02
      finalState: approved
  install_50:
    stage: canary50
    image: 'codefresh/cfstep-helm:2.9.1'
    title: Install
    environment:
      - CHART_REF=blog/blog
      - RELEASE_NAME=blog
      - KUBE_CONTEXT=chopper
      - NAMESPACE=applications
      - VALUESFILE_prod='blog/blog/values.yaml'
      - VALUE_image_repository='r.cfcr.io/abatilo/abatilo/blog'
      - VALUE_image_tag='${{PREVIOUS_VERSION}}'
      - VALUE_canary_enabled=true
      - VALUE_canary_percentage=50
      - VALUE_canary_tag='${{VERSION}}'
  timeout_50:
    stage: canary50
    type: pending-approval
    title: Step Title
    description: Step description
    timeout:
      duration: 0.02
      finalState: approved
  install_75:
    stage: canary75
    image: 'codefresh/cfstep-helm:2.9.1'
    title: Install
    environment:
      - CHART_REF=blog/blog
      - RELEASE_NAME=blog
      - KUBE_CONTEXT=chopper
      - NAMESPACE=applications
      - VALUESFILE_prod='blog/blog/values.yaml'
      - VALUE_image_repository='r.cfcr.io/abatilo/abatilo/blog'
      - VALUE_image_tag='${{PREVIOUS_VERSION}}'
      - VALUE_canary_enabled=true
      - VALUE_canary_percentage=75
      - VALUE_canary_tag='${{VERSION}}'
  timeout_75:
    stage: canary75
    type: pending-approval
    title: Step Title
    description: Step description
    timeout:
      duration: 0.02
      finalState: approved
  install_100:
    stage: release
    image: 'codefresh/cfstep-helm:2.9.1'
    title: Install
    environment:
      - CHART_REF=blog/blog
      - RELEASE_NAME=blog
      - KUBE_CONTEXT=chopper
      - NAMESPACE=applications
      - VALUESFILE_prod='blog/blog/values.yaml'
      - VALUE_image_repository='r.cfcr.io/abatilo/abatilo/blog'
      - VALUE_image_tag='${{PREVIOUS_VERSION}}'
      - VALUE_canary_enabled=false
      - VALUE_canary_percentage=100
      - VALUE_canary_tag='${{VERSION}}'
