version: '1.0'
stages:
  - build
  - timeout_25
  - timeout_50
  - timeout_75
  - release
steps:
  clone:
    stage: build
    title: Clone
    type: git-clone
    arguments:
      repo: 'abatilo/blog'
      git: github
      revision: 'master'
  previous_version:
    stage: build
    title: Get Previous Version
    type: freestyle
    arguments:
      image: 'codefresh/kubectl:latest'
      working_directory: 'blog/'
      commands:
        - cf_export PREVIOUS_VERSION=$(kubectl --context chopper -n applications get deployment blog -o jsonpath='{.spec.template.spec.containers[0].image}' | cut -d':' -f2)
  version:
    stage: build
    title: Get Version
    type: freestyle
    arguments:
      image: 'alpine:latest'
      working_directory: 'blog/'
      commands:
        - cf_export VERSION=$(cat version.txt)
  build:
    stage: build
    title: Build
    type: build
    image_name: 'abatilo/blog'
    working_directory: 'blog'
    tag: ${{VERSION}}
  install_25:
    stage: timeout_25
    fail_fast: false
    image: 'codefresh/cfstep-helm:2.9.1'
    title: Install at 25%
    environment:
      - CHART_REF=blog/blog
      - RELEASE_NAME=blog
      - KUBE_CONTEXT=chopper
      - NAMESPACE=applications
      - VALUESFILE_prod='blog/blog/values.yaml'
      - VALUE_image_repository='r.cfcr.io/abatilo/abatilo/blog'
      - VALUE_image_tag='${{PREVIOUS_VERSION}}'
      - VALUE_canary_enabled=true
      - VALUE_canary_percentage=25
      - VALUE_canary_tag='${{VERSION}}'
  timeout_25:
    stage: timeout_25
    type: pending-approval
    fail_fast: false
    title: Waiting with 25%
    description: Step description
    timeout:
      duration: 0.005
      finalState: approved
  install_50:
    stage: timeout_50
    fail_fast: false
    image: 'codefresh/cfstep-helm:2.9.1'
    title: Install at 50%
    environment:
      - CHART_REF=blog/blog
      - RELEASE_NAME=blog
      - KUBE_CONTEXT=chopper
      - NAMESPACE=applications
      - VALUESFILE_prod='blog/blog/values.yaml'
      - VALUE_image_repository='r.cfcr.io/abatilo/abatilo/blog'
      - VALUE_image_tag='${{PREVIOUS_VERSION}}'
      - VALUE_canary_enabled=true
      - VALUE_canary_percentage=50
      - VALUE_canary_tag='${{VERSION}}'
    when:
      condition:
        all:
          timeout_25Approved: steps.timeout_25.result == 'approved'
  timeout_50:
    stage: timeout_50
    fail_fast: false
    type: pending-approval
    title: Waiting at 50%
    description: Step description
    timeout:
      duration: 0.005
      finalState: approved
    when:
      condition:
        all:
          timeout_25Approved: steps.timeout_25.result == 'approved'
  install_75:
    stage: timeout_75
    fail_fast: false
    image: 'codefresh/cfstep-helm:2.9.1'
    title: Install at 75%
    environment:
      - CHART_REF=blog/blog
      - RELEASE_NAME=blog
      - KUBE_CONTEXT=chopper
      - NAMESPACE=applications
      - VALUESFILE_prod='blog/blog/values.yaml'
      - VALUE_image_repository='r.cfcr.io/abatilo/abatilo/blog'
      - VALUE_image_tag='${{PREVIOUS_VERSION}}'
      - VALUE_canary_enabled=true
      - VALUE_canary_percentage=75
      - VALUE_canary_tag='${{VERSION}}'
    when:
      condition:
        all:
          timeout_25Approved: steps.timeout_25.result == 'approved'
          timeout_50Approved: steps.timeout_50.result == 'approved'
  timeout_75:
    stage: timeout_75
    fail_fast: false
    type: pending-approval
    title: Waiting at 75%
    description: Step description
    timeout:
      duration: 0.005
      finalState: approved
    when:
      condition:
        all:
          timeout_25Approved: steps.timeout_25.result == 'approved'
          timeout_50Approved: steps.timeout_50.result == 'approved'
  install_100:
    stage: release
    image: 'codefresh/cfstep-helm:2.9.1'
    title: Install at 100%
    environment:
      - CHART_REF=blog/blog
      - RELEASE_NAME=blog
      - KUBE_CONTEXT=chopper
      - NAMESPACE=applications
      - VALUESFILE_prod='blog/blog/values.yaml'
      - VALUE_image_repository='r.cfcr.io/abatilo/abatilo/blog'
      - VALUE_image_tag='${{VERSION}}'
      - VALUE_canary_enabled=false
    when:
      condition:
        all:
          timeout_25Approved: steps.timeout_25.result == 'approved'
          timeout_50Approved: steps.timeout_50.result == 'approved'
          timeout_75Approved: steps.timeout_75.result == 'approved'
  revert:
    stage: release
    image: 'codefresh/cfstep-helm:2.9.1'
    title: Revert
    environment:
      - CHART_REF=blog/blog
      - RELEASE_NAME=blog
      - KUBE_CONTEXT=chopper
      - NAMESPACE=applications
      - VALUESFILE_prod='blog/blog/values.yaml'
      - VALUE_image_repository='r.cfcr.io/abatilo/abatilo/blog'
      - VALUE_image_tag='${{PREVIOUS_VERSION}}'
      - VALUE_canary_enabled=false
      - VALUE_canary_percentage=100
      - VALUE_canary_tag='${{VERSION}}'
    when:
      condition:
        any:
          timeout_25Approved: steps.timeout_25.result != 'approved'
          timeout_50Approved: steps.timeout_50.result != 'approved'
          timeout_75Approved: steps.timeout_75.result != 'approved'
