name: Deploy
on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Log in to GitHub Docker Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ghcr.io/abatilo/blog:${{ github.sha }}
          context: .
          file: ./Dockerfile
          labels: |
            org.opencontainers.image.source=https://github.com/abatilo/blog
