name: Deploy
on:
  pull_request: {}
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    concurrency: deploy
    permissions:
      packages: write
      contents: read
    steps:
      - uses: docker://chinthakagodawita/autoupdate-action@sha256:f0db4944adb5eb64565d4b2f8bb2b3f767a7224327d217c272935d21dbe7b541 # dockerhub sha
      - uses: chinthakagodawita/autoupdate-action@95c97b013bcd901adb6b42831b9db8552b9a330f # git sha
        if: always()
        
      - uses: actions/checkout@v2
      - uses: asdf-vm/actions/install@v1
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v2
        with:
          push: true
          tags: ghcr.io/abatilo/blog:${{ github.sha }}
          context: .
          file: ./Dockerfile
          labels: |
            org.opencontainers.image.source=https://github.com/abatilo/blog

      - name: Deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-west-2
        run: |
          aws sts get-caller-identity
          aws eks update-kubeconfig --name abatilo-cloud-tf
          sed -i 's/DOCKER_TAG/${{ github.sha }}/' blog.yaml
          kubectl apply -f blog.yaml
