name: Pulumi
on:
  push:
    branches:
      - master

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: "us-west-2"
  AWS_DEFAULT_REGION: "us-west-2"
jobs:
  up:
    name: Update
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.1

      # Install asdf dependencies
      - name: asdf setup
        uses: asdf-vm/actions/setup@v1.0.0
      - name: asdf plugin add
        run: |
          asdf plugin-add pulumi https://github.com/canha/asdf-pulumi.git
          asdf plugin-add hugo https://github.com/beardix/asdf-hugo.git
          asdf plugin-add nodejs https://github.com/asdf-vm/asdf-nodejs.git
      - name: asdf install
        env:
          NODEJS_CHECK_SIGNATURES: "no"
        run: |
          asdf install

      # npm dependencies
      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Install npm dependencies
        run: |
          npm ci

      # Perform deployment
      - name: Create lock
        uses: abatilo/github-action-locks@master
        with:
          name: "blog-${{ github.workflow }}"
      - name: Deploy
        env:
          PULUMI_CONFIG_PASSPHRASE: ${{ secrets.PULUMI_CONFIG_PASSPHRASE }}
        run: |
          pulumi up -s blog --yes --skip-preview
