name: Pulumi
on:
  push:
    branches:
      - master

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: "us-west-2"
  AWS_DEFAULT_REGION: "us-west-2"
jobs:
  up:
    name: Update
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Create lock
        uses: abatilo/github-action-locks@master
        with:
          name: "blog-${{ github.workflow }}"
      - name: asdf_install
        uses: asdf-vm/actions/install@v1.0.0
        env:
          NODEJS_CHECK_SIGNATURES: "no"
      - env:
          PULUMI_CONFIG_PASSPHRASE: ${{ secrets.PULUMI_CONFIG_PASSPHRASE }}
        run: |
          npm ci
          pulumi up -s blog --yes --skip-preview
