name: "Check for mean comments"
on:
  issue_comment:
    types:
      - created
      - edited

jobs:
  sentiment:
    runs-on: ubuntu-latest
    if: ${{ github.event.issue.pull_request }}
    steps:
      - env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          commenter="${{ github.event.comment.user.login }}"
          owner="${{ github.event.repository.owner.login }}"
          repo="${{ github.event.repository.name}}"
          pull_number="${{ github.event.issue.number }}"
          issue_id="${{ github.event.issue.id }}"

          echo ${owner}
          echo ${repo}
          echo ${pull_number}
          echo ${issue_id}

          # hub api /repos/${owner}/${repo}/pulls/${pull_number}/comments/${issue_id}/replies -f body="from action"
          hub api /repos/${owner}/${repo}/issues/${pull_number}/comments -f body="@${commenter} from action"
